# Generated by Django 5.2 on 2025-07-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=255)),
                ("pleasant_habit", models.BooleanField(default=False)),
                ("frequency", models.PositiveIntegerField(default=1)),
                ("reward", models.CharField(blank=True, max_length=255, null=True)),
                ("time_to_complete", models.PositiveIntegerField()),
                ("is_public", models.BooleanField(default=False)),
                ("last_performed", models.DateTimeField(blank=True, null=True)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habit",
                "verbose_name_plural": "Habits",
            },
        ),
    ]
